---
- name: 'Instala paquetes para OpenVPN'
  yum:
    name:
      "{{ paquetes_nscp }}"
    state: present

- name: 'Elimina configuración por defecto'
  file:
    state: absent
    path: '/etc/nsclient/'

- name: 'Configuracion'
  git:
    repo: '{{ git_nscp }}'
    dest: '/etc/nsclient'
    clone: yes

- name: 'Servizo'
  systemd:
    state: started
    enabled: yes
    name: nsclient.service